In [53]:
# インサートソート
N = int(input())
L = list(map(int,input().split()))

for i in range(N):
    for j in range(i):
        if L[i] < L[j]:
            ins = L[i]
            L[j+1:i+1] = L[j:i]
            L[j] = ins
            print(L)

[4, 5, 2, 3, 1, 6]
[2, 4, 5, 3, 1, 6]
[2, 3, 4, 5, 1, 6]
[1, 2, 3, 4, 5, 6]


In [62]:
# バブルソート
N = int(input())
L = list(map(int,input().split()))

for i in range(1,N):
    for j in range(1,N-i+1):
        if L[-j] < L[-j-1]:
            tmp = L[-j]
            L[-j] = L[-j-1]
            L[-j-1] = tmp
        print(L)

[5, 3, 2, 1, 4]
[5, 3, 1, 2, 4]
[5, 1, 3, 2, 4]
[1, 5, 3, 2, 4]
[1, 5, 3, 2, 4]
[1, 5, 2, 3, 4]
[1, 2, 5, 3, 4]
[1, 2, 5, 3, 4]
[1, 2, 3, 5, 4]
[1, 2, 3, 4, 5]


In [11]:
# n! 再帰関数
def func(n):
    #print(n)
    if n == 1:
        return 1
    return n*func(n-1)
n = 7
print(func(n))

5040


In [64]:
# 全探索（組み合わせの列挙）
#i = 5
#print(bin(i))
#print(bin(i >> 2))
#print((i >> 2)&1)

money = 300
items = {'みかん':100,'りんご':200,'メロン':300,'ぶどう':150}

N = len(items)

for i in range(2**N):
    bag = []
    cost = 0
    print('購入パターン:{}'.format(i), end ='')
    for j,food in enumerate(items.items()):
        if ((i >> j)&1):
            bag.append(food[0])
            cost += food[1]
    print(bag,'合計{}円'.format(cost))

購入パターン:0[] 合計0円
購入パターン:1['みかん'] 合計100円
購入パターン:2['りんご'] 合計200円
購入パターン:3['みかん', 'りんご'] 合計300円
購入パターン:4['メロン'] 合計300円
購入パターン:5['みかん', 'メロン'] 合計400円
購入パターン:6['りんご', 'メロン'] 合計500円
購入パターン:7['みかん', 'りんご', 'メロン'] 合計600円
購入パターン:8['ぶどう'] 合計150円
購入パターン:9['みかん', 'ぶどう'] 合計250円
購入パターン:10['りんご', 'ぶどう'] 合計350円
購入パターン:11['みかん', 'りんご', 'ぶどう'] 合計450円
購入パターン:12['メロン', 'ぶどう'] 合計450円
購入パターン:13['みかん', 'メロン', 'ぶどう'] 合計550円
購入パターン:14['りんご', 'メロン', 'ぶどう'] 合計650円
購入パターン:15['みかん', 'りんご', 'メロン', 'ぶどう'] 合計750円


In [5]:
# クラスの継承
class A:
    def __init__(self):
        print('A is created')

class B(A):
    def __init__(self):
        super().__init__()
        print('B is created')

print(B())

A is created
B is created


In [8]:
# 固有値
import numpy as np
import numpy.linalg as LA

a = np.array([[5,3],
              [4,9]])

LA.eig(a)

(array([ 3., 11.]),
 array([[-0.83205029, -0.4472136 ],
        [ 0.5547002 , -0.89442719]]))

In [17]:
# range関数
[i for i in range(11) if i%2==0]

[0, 2, 4, 6, 8, 10]

In [12]:
# 行列計算
import numpy as np

ones = np.ones(6)
ones = ones.reshape(2,3)

sample = [[1,2,3],
         [4,5,6]]

print(ones+sample)

[[2. 3. 4.]
 [5. 6. 7.]]


In [15]:
# KLダイバージェンス
from scipy.stats import norm,entropy

p = 0.5
q = 0.9

slf_ent = -1*(q*np.log(q) +(1-q)*np.log(1-q))
crs_ent = -1*(q*np.log(p) +(1-q)*np.log(1-p))

print('slf_ent',slf_ent)
print('crs_ent',crs_ent)
print(crs_ent -slf_ent)
print(entropy([q,1-q],[p,1-p]))

slf_ent 0.3250829733914482
crs_ent 0.6931471805599453
0.3680642071684971
0.36806420716849714


In [16]:
# ユークリッド互除法
A,B = 12,34

while B != 0:
    
    C = A%B
    A = B
    B = C
print('最大公約数：',A)

最大公約数： 2


In [23]:
# 条件分岐
A = [-1,0,3,1,-3,0]
for a in A:
    if a > 0:
        print('{: 3} is bigger than 0'.format(a))
    elif a < 0:
        print('{: 3} is smaller than 0'.format(a))
    else:
        print('{: 3} is equall to 0'.format(a))

 -1 is smaller than 0
  0 is equall to 0
  3 is bigger than 0
  1 is bigger than 0
 -3 is smaller than 0
  0 is equall to 0


In [ ]:
# 2分探索


In [24]:
# 主成分分析 PCA
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

boston = load_boston()
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df.head()

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [27]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# データの標準化
sc = StandardScaler()
df_sc = sc.fit_transform(df)

# データの主成分分析
pca = PCA(n_components=3)
pca_df = pca.fit_transform(df_sc)

print('固有値:',pca.explained_variance_)
print('寄与率:',pca.explained_variance_ratio_)
print('固有ベクトル:\n',pca_df)

固有値: [6.1389812  1.43611329 1.2450773 ]
寄与率: [0.47129606 0.11025193 0.0955859 ]
固有ベクトル:
 [[-2.09829747  0.77311275  0.34294273]
 [-1.45725167  0.59198521 -0.69519931]
 [-2.07459756  0.5996394   0.1671216 ]
 ...
 [-0.31236047  1.15524644 -0.40859759]
 [-0.27051907  1.04136158 -0.58545406]
 [-0.12580322  0.76197805 -1.294882  ]]


In [ ]:
# X以上の最小の素数探索

def check(num):
    for j in range(2,int(num**0.5)+1):
        if num%j == 0:
            return False

    return True

X = int(input())

for x in range(X,2*X):
    if check(x):
        print(x)
        break

In [34]:
# シンメトリック　サーチ
N = int(input())

pair = []
for n in range(N):
    i,j = map(int,input().split())
    
    pair.append((i,j))
    #print(pair)
    for k,l in pair:
        if i == l and j == k:
            print(i,j)

[(1, 2)]
[(1, 2), (2, 1)]
2 1
[(1, 2), (2, 1), (3, 2)]


In [36]:
# 順列の列挙
import itertools

N = int(input())
perm = list(itertools.permutations(range(1,N+1)))
print(perm)

[(1, 2, 3, 4), (1, 2, 4, 3), (1, 3, 2, 4), (1, 3, 4, 2), (1, 4, 2, 3), (1, 4, 3, 2), (2, 1, 3, 4), (2, 1, 4, 3), (2, 3, 1, 4), (2, 3, 4, 1), (2, 4, 1, 3), (2, 4, 3, 1), (3, 1, 2, 4), (3, 1, 4, 2), (3, 2, 1, 4), (3, 2, 4, 1), (3, 4, 1, 2), (3, 4, 2, 1), (4, 1, 2, 3), (4, 1, 3, 2), (4, 2, 1, 3), (4, 2, 3, 1), (4, 3, 1, 2), (4, 3, 2, 1)]


In [40]:
# FizzBuzz
for i in range(1,21):
    if i%3 == 0 and i%5 == 0:
        print(i,'FizzBuzz')
    elif i%3 == 0:
        print(i,'Fizz')
    elif i%5 == 0:
        print(i,'Buzz')
    else:
        print(i)

1
2
3 Fizz
4
5 Buzz
6 Fizz
7
8
9 Fizz
10 Buzz
11
12 Fizz
13
14
15 FizzBuzz
16
17
18 Fizz
19
20 Buzz


In [ ]:
# ビンゴ
card = {}
comb = []
for _ in range(3):
    A = list(map(int,input().split()))
    comb.append(A)
    for num in A:
        card[num] = 0
        
#縦組み合わせ
tmp1 = []
tmp2 = []
tmp3 = []
tmp4 = []
tmp5 = []
for i,num in enumerate(comb):
    tmp1.append(num[0])
    tmp2.append(num[1])
    tmp3.append(num[2])
    tmp4.append(num[i])
    tmp5.append(num[2-i])

comb.append(tmp1)
comb.append(tmp2)
comb.append(tmp3)
comb.append(tmp4)
comb.append(tmp5)

def check():
    for n in comb:
        flag = 0
        for m in n:
            flag += card[m]

        if flag == 3:
            return True
    return False

N = int(input())
ans = 0
for _ in range(N):
    b = int(input())

    if b in card:
        card[b] = 1
    
    if check():
        ans = 1
        break
print('Yes' if ans == 1 else 'No')

In [1]:
# リストを1行ずつ出力する
A= [0,1,1,2]
print('\n'.join(map(str,A)))

0
1
1
2


In [12]:
# 時刻変換
s = 46979

h = s//3600
print(h)
m = (s-h*3600)//60
print(m)
s = (s-h*3600-m*60)
print(s)
print(str(h)+':'+str(m)+':'+str(s))

13
2
59
13:2:59


In [29]:
# 集合
A = 'aaabbbcccf'
B = 'abc'
C = 'abcdee'

A = set(A)
B = set(B)
C = set(C)
print('',A,'\n',B,'\n',C)
print('A<=B',A<=B)
print('B<=A',B<=A)
print('A<=C',A<=C)
print('B<=C',B<=C)
print('A&B', A&B)
print('A&C', A&C)
print('B&C', B&C)
print('A|B', A|B)
print('A-B', A-B)
print('C-B', C-B)
print('A^B',A^B)
print('A^C',A^C)

 {'f', 'c', 'b', 'a'} 
 {'c', 'b', 'a'} 
 {'d', 'e', 'c', 'b', 'a'}
A<=B False
B<=A True
A<=C False
B<=C True
A&B {'c', 'b', 'a'}
A&C {'c', 'b', 'a'}
B&C {'c', 'b', 'a'}
A|B {'f', 'c', 'b', 'a'}
A-B {'f'}
C-B {'d', 'e'}
A^B {'f'}
A^C {'f', 'd', 'e'}


In [ ]:
# ミンコフスキー距離
n = int(input())
x = list(map(int,input().split()))
y = list(map(int,input().split()))

for i in range(1,5):
    t = 0
    if i != 4:
        for num in range(n):
            t += abs(x[num]-y[num])**i
        print(t**(1/i))
    else:
        # ∞のとき
        for num in range(n):
            if t < abs(x[num]-y[num]):
                t = abs(x[num]-y[num])
        print(t)

In [ ]:
# 分散、標準偏差
while True:

    n = int(input())
    if n == 0:
        break

    m = list(map(int,input().split()))
    ave = sum(m)/n

    var = 0
    for i in range(n):
        var += (m[i]-ave)**2
    print((var/n)**0.5)